In [1]:
import gensim.downloader as api
from gensim.models import KeyedVectors,Word2Vec

In [2]:
model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
model.save('/content/GoogleNews-vectors-negative300.bin')

In [4]:
model_path = '/content/GoogleNews-vectors-negative300.bin'

In [5]:
model = KeyedVectors.load('/content/GoogleNews-vectors-negative300.bin')

In [6]:
model['man'].shape

(300,)

In [7]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [8]:
model['bottle']

array([-0.02941895,  0.11767578, -0.15039062,  0.00192261, -0.11230469,
        0.30273438,  0.38476562, -0.2734375 ,  0.23828125,  0.29492188,
       -0.08056641, -0.48242188,  0.05664062, -0.01623535, -0.31054688,
        0.14941406, -0.16308594,  0.26757812,  0.09521484, -0.109375  ,
        0.24414062,  0.09228516, -0.02404785, -0.15136719, -0.13769531,
        0.18066406,  0.02270508,  0.26171875,  0.11230469,  0.12695312,
        0.12060547, -0.00159454, -0.24511719,  0.04833984, -0.08935547,
        0.00787354,  0.14257812, -0.04736328, -0.15039062, -0.00081253,
       -0.33984375,  0.109375  ,  0.34570312, -0.11669922,  0.10253906,
       -0.15234375, -0.02868652,  0.07324219,  0.11669922, -0.25390625,
       -0.38867188, -0.10693359,  0.02441406, -0.31054688,  0.0534668 ,
       -0.07275391,  0.14453125,  0.15332031, -0.06225586, -0.07177734,
       -0.27929688,  0.05224609,  0.13964844, -0.02282715, -0.08642578,
       -0.11572266,  0.05932617, -0.3359375 ,  0.34179688, -0.03

In [9]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [10]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [11]:
model.similarity('man','woman')

0.76640123

In [12]:
model.similarity('man','PHP')

-0.032995153

In [13]:
model.doesnt_match(['PHP','java','monkey'])

'monkey'

In [14]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [15]:
vec = model['INR'] - model['India'] + model['China']
model.most_similar([vec])

[('INR', 0.7739980220794678),
 ('RMB', 0.6375728845596313),
 ('CNY##', 0.6112409830093384),
 ('yuan', 0.5944303870201111),
 ('CNY###', 0.5918893814086914),
 ('RMB3', 0.589189350605011),
 ('CNY', 0.5873592495918274),
 ('RMB###', 0.569147527217865),
 ('Rmb##', 0.56504887342453),
 ('RMB8', 0.5594514608383179)]

In [16]:
import numpy as np
import pandas as pds
import os
import gensim
import json
from zipfile import ZipFile

In [17]:
!kaggle datasets download -d khulasasndh/game-of-thrones-books

Dataset URL: https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books
License(s): unknown
  0% 0.00/3.71M [00:00<?, ?B/s]
100% 3.71M/3.71M [00:00<00:00, 44.4MB/s]


In [19]:
kaggle_credentials = json.load(open("kaggle.json"))

In [20]:
!unzip game-of-thrones-books.zip -d game-of-thrones-books

Archive:  game-of-thrones-books.zip
  inflating: game-of-thrones-books/001ssb.txt  
  inflating: game-of-thrones-books/002ssb.txt  
  inflating: game-of-thrones-books/003ssb.txt  
  inflating: game-of-thrones-books/004ssb.txt  
  inflating: game-of-thrones-books/005ssb.txt  


In [21]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [22]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir('/content/game-of-thrones-books'):
  with open('/content/game-of-thrones-books/'+filename, encoding='Windows-1252') as f:
    corpus = f.read()
  raw_sent = sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [23]:
len(story)

145020

In [24]:
model = gensim.models.Word2Vec(window=10,min_count=2,workers=4)

In [25]:
model.build_vocab(story)

In [26]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(6569210, 8628190)

In [27]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8086167573928833),
 ('queen', 0.7353664040565491),
 ('targaryen', 0.7007834315299988),
 ('princess', 0.664178729057312),
 ('unburnt', 0.662218451499939),
 ('myrcella', 0.649945855140686),
 ('viserys', 0.647840678691864),
 ('margaery', 0.6457672119140625),
 ('dorne', 0.6302615404129028),
 ('khaleesi', 0.6176608204841614)]

In [28]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [29]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [30]:
model.wv['king']

array([ 2.0510519 ,  0.3844732 , -0.96028996,  2.0938795 , -3.032704  ,
        3.453379  , -1.7453606 , -0.4733403 , -1.8049762 , -0.20273499,
       -0.6471936 , -3.036754  ,  0.5178293 ,  3.3016355 , -2.184578  ,
        0.36467433, -1.2598133 ,  2.6174624 , -0.44184503,  1.1016457 ,
       -0.34265816,  0.34034583,  2.1157708 , -1.1454405 , -1.7484661 ,
       -0.34105423, -1.70217   ,  0.5660155 , -1.4779236 ,  1.135742  ,
       -2.4233081 ,  0.54134035,  0.3381051 ,  0.23104657, -0.19409873,
       -2.430009  , -2.5120835 ,  0.36852413,  1.0986364 , -1.898342  ,
        1.597821  ,  1.6997724 ,  2.1774368 , -0.45878267, -0.714171  ,
       -0.48696   , -0.01648477, -4.9251075 ,  2.8757484 , -1.708764  ,
       -3.3170378 , -0.17218418, -2.2134898 , -1.60998   ,  4.538107  ,
       -1.2008681 ,  0.72394985, -0.27075684,  0.42137903,  0.35911328,
        1.4273099 ,  1.6788616 ,  1.3507173 ,  2.7148812 , -0.79261273,
       -0.49015653, -1.8770543 , -1.4229751 , -1.9229399 , -1.07

In [31]:
model.wv.similarity('arya','sansa')

0.8747631

In [32]:
model.wv.similarity('cersei','sansa')

0.7131523

In [33]:
model.wv.get_normed_vectors()

array([[-0.03818441, -0.0490794 ,  0.06829681, ..., -0.07303494,
         0.03395651,  0.14668427],
       [-0.09469038, -0.04122288,  0.04697543, ..., -0.01148441,
        -0.04049474,  0.15109979],
       [ 0.21262528, -0.09609239, -0.22456257, ..., -0.00436561,
         0.1406361 , -0.21450368],
       ...,
       [-0.02574637,  0.02665018,  0.03164694, ...,  0.01295011,
         0.15052941, -0.11007456],
       [ 0.00032248,  0.07742383,  0.11605297, ..., -0.04351674,
        -0.03698301, -0.05388062],
       [ 0.00539121,  0.01586817,  0.13664716, ..., -0.19669831,
        -0.02566627, -0.03045388]], dtype=float32)

In [34]:
y = model.wv.index_to_key

In [35]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [36]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [37]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [38]:
X[:5]

array([[-0.15896119,  0.57601905, -0.01622955],
       [-0.13931267,  0.34959236,  0.04923771],
       [ 0.2981694 ,  0.57399756,  0.20711876],
       [ 0.00148741,  0.36951855, -0.1134359 ],
       [ 0.13866639,  0.5477668 ,  0.29364958]], dtype=float32)

In [39]:
import plotly.express as px
fig = px.scatter_3d(X[:100],x=0,y=1,z=2,color=y[:100])
fig.show()